Add some more linting rules
sealwadding/blog pull request #21
Opened 2021-05-20 19:55 UTC by markgaze

This is a start, I've moved over some rules we usually use and ones that I've used on other Next projects.

We can keep building them up and there's a few areas of the code that have warnings left but we can get through them eventually!

2021-05-20 19:56 UTC, markgaze commented
#### 📝Changed routes:


| [**/author/\[id\]**](https://sealwadding-blog-6wjbl2wsp-markgaze.vercel.app/author/[id]) | [**/authors**](https://sealwadding-blog-6wjbl2wsp-markgaze.vercel.app/authors) |
|:-:|:-:|
|<a href="https://sealwadding-blog-6wjbl2wsp-markgaze.vercel.app/author/[id]"><img src="https://images.weserv.nl?url=https://iad.microlink.io/1yQ2CxAmpRf8eyNr3BidqjzvX9AWW-jJNoEzgfSl1PPQ-hJkwpaLk-aE5sSFNUANQQfSC_iviUtIPX7U0fmCwA.png&w=600" alt="Screenshot of /author/[id]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/D13_DxIIpAP0-5FMDgYnU8NbCy0TKtyWly5L6R5mJ2_kJt3l3lZLiCvO1SFysalT7Ba7IeXwoaScJlyc7ouDRQ.png">(view full size)</a> |<a href="https://sealwadding-blog-6wjbl2wsp-markgaze.vercel.app/authors"><img src="https://images.weserv.nl?url=https://iad.microlink.io/2oWg_08ugXTaQncsEOS152fOcZCWOvqiH976XqsiOt3Uq3HEgdG2jxD9bs-0SSbY_ydzMmcAG6wceXuCPFuuSQ.png&w=600" alt="Screenshot of /authors" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/fonzDY-d0JiMkD3f--QLc0s31SBGfgqJLPrFQxlYbvuESRPcjTmk6t15mLHjpMEdtBvQCKrufzQ5cGeaWD1tOw.png">(view full size)</a> |



| [**/**](https://sealwadding-blog-6wjbl2wsp-markgaze.vercel.app/) | [**/post/\[id\]**](https://sealwadding-blog-6wjbl2wsp-markgaze.vercel.app/post/[id]) |
|:-:|:-:|
|<a href="https://sealwadding-blog-6wjbl2wsp-markgaze.vercel.app/"><img src="https://images.weserv.nl?url=https://iad.microlink.io/rrRJJJQrTEW-1ZE7IfWONvjAiyXdTzTw_wNA7SZaCZ6IbqCQrJKcYrV2ovC6joLKKoS_6ZWJJjsiCjH1-DVXuw.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/yuKCKBjjpn2EThtd6bK0Q9L3GLUb73q19nU_SmBalQDC3eSW-_2yUNCGrCq6ySUpC-msUZAzioko0wU9s978oA.png">(view full size)</a> |<a href="https://sealwadding-blog-6wjbl2wsp-markgaze.vercel.app/post/[id]"><img src="https://images.weserv.nl?url=https://iad.microlink.io/HBD5h9PQtXOTYNpjUtBB79h-nv-OwoQYLyN0vFbg6FXYIHHvB-pGOSDWXwYB0ef3_2mrw3WUb4_eHt-MvpSI6A.png&w=600" alt="Screenshot of /post/[id]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/gZ6-QzkBhjEiJtxv20xGpCP2z3DeVV7oYhfiUa5g0HHxh3ZpuLohOZwYssLBxJ1VBHoXdZ5o2cQfZb3FOuZ5wA.png">(view full size)</a> |



And 1 other route:
- [**/api/hello**](https://sealwadding-blog-6wjbl2wsp-markgaze.vercel.app/api/hello)



Commit 3670ce49ec782e5fda33946e7deffaeb3df315cb (https://sealwadding-blog-6wjbl2wsp-markgaze.vercel.app).

2021-05-20 20:29 UTC, andrewbarnesweb requested changes
Holy smokes! You have been busy!

2021-05-20 20:29 UTC, andrewbarnesweb commented on .stylelintrc
> +    'selector-class-pattern': [
Reckon we can ditch this, as we're using CSS Modules 🙂

2021-05-21 09:12 UTC, markgaze commented
I accidentally included the `.vscode` settings folder so if you want me to take it out, I can but I know we've committed it to some repos

2021-05-21 11:19 UTC, andrewbarnesweb commented
Nah looks good. Not looking forward to rebasing onto this though 😂

2021-05-21 11:19 UTC, andrewbarnesweb approved these changes

2021-05-21 11:19 UTC, merged